const path = require('path');
const fse = require('fs-extra');

const usage = "node juxta2usfm.js <jxlPath> <bookCode>";
if (process.argv.length !== 4) {
    console.log(usage);
    process.exit(1);
}
const juxta = fse.readJsonSync(process.argv[2]);
const bookCode = process.argv[3];
let usfmBits = [
    `\\id ${bookCode} generated by Xenizo using juxta2usfm`,
    '\\usfm 3.0',
    `\\h ${bookCode}`,
    `\\toc1 ${bookCode}`,
    `\\toc2 ${bookCode}`,
    `\\toc3 ${bookCode}`,
    `\\mt ${bookCode}`
];
let sentenceN = 1;
for (const sentence of juxta) {
    let isFirst = true;
    usfmBits.push(`\\s Phrase ${sentenceN}`);
    for (const chunk of sentence.chunks) {
        const greekChunk = chunk.source.map(c => c.content).join(' ');
        const glossChunk = chunk.gloss.replace(/\*([^*]+)\*/g,(all, inner) => `\\it ${inner}\\it*`);
        usfmBits.push(isFirst ? '\\m' : "\\p");
        usfmBits.push(`${glossChunk} \\f + \\tl ${greekChunk}\\tl*\\f*`);
        isFirst = false;
    }
    sentenceN++;
}

console.log(usfmBits.join('\r\n'));
